package com.mir2.world;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Authoritative monster catalogue imported from the official 1.76 {@code Monster.DB}
 * (GEEM2 baseline dump, see {@code db/MonsterDb.tsv} header for provenance). The Java
 * counterpart of the Delphi {@code TMonInfo} rows that {@code TFrmDB.LoadMonsterDB}
 * (LocalDB.pas:1288) loads into {@code UserEngine.MonsterList}.
 *
 * <p>Field mapping follows Grobal2.pas:1555 {@code TMonInfo} and the assignment block in
 * UsrEngn.pas:2581 ({@code OpenMonster}-style initialisation): {@code hp}/{@code mp} are
 * the server-side pools (Delphi additionally multiplies them by
 * {@code g_Config.nMonsterPowerRate / 10}, default 10 = no scaling), {@code ac}/{@code mac}
 * are flat values and {@code dc}..{@code dcMax} the attack range; {@code walkSpd} becomes
 * {@code m_nWalkSpeed} and {@code attackSpd} becomes {@code m_nNextHitTime}, both clamped
 * to a 200&nbsp;ms floor by {@code LoadMonsterDB}. The low byte of {@code mp} doubles as
 * the monster weapon byte for {@code MakeMonsterFeature} ({@code m_btMonsterWeapon}).
 *
 * <p>The full 378-row table is imported as data. The engine's red line still applies:
 * only the first-ten templates plus the trainer dummy are wired to behaviour; the rest of
 * the table is reference data for future slices (and for pinning the implemented ones).
 */
public final class MonsterDb {

  /** One {@code Monster} table row, native columns in dump order. */
  public record Row(
      String name, int race, int raceImg, int appr, int level, int undead, int coolEye,
      long exp, int hp, int mp, int ac, int mac, int dc, int dcMax, int mc, int sc,
      int speed, int hit, int walkSpd, int walkStep, int walkWait, int attackSpd) {

    public Row {
      if (name == null || name.isBlank()) throw new IllegalArgumentException("monster name must not be blank");
      if (exp < 0) throw new IllegalArgumentException("exp must not be negative");
    }

    /** The monster weapon byte ({@code m_btMonsterWeapon = LoByte(MP)}, UsrEngn.pas:2595). */
    public int monsterWeapon() {
      return mp & 0xFF;
    }
  }

  /** Classpath location of the imported TSV (generated by {@code scripts/extract-geem2-db.py}). */
  public static final String RESOURCE = "/db/MonsterDb.tsv";

  /** {@code LoadMonsterDB} clamps both action intervals to a 200 ms floor. */
  public static final int MIN_ACTION_INTERVAL_MS = 200;

  private static volatile List<Row> cached;

  /** All 378 imported rows, in original dump order. */
  public static List<Row> all() {
    List<Row> rows = cached;
    if (rows == null) {
      rows = List.copyOf(parse(open(RESOURCE)));
      cached = rows;
    }
    return rows;
  }

  /** First row with the given (client-visible) name — Monster.DB names are unique. */
  public static Optional<Row> byName(String name) {
    return all().stream().filter(row -> row.name().equals(name)).findFirst();
  }

  /** Applies the {@code LoadMonsterDB} clamp: values below 200 ms are raised to 200. */
  public static int clampActionInterval(int millis) {
    return Math.max(MIN_ACTION_INTERVAL_MS, millis);
  }

  static List<Row> parse(BufferedReader reader) {
    List<Row> rows = new ArrayList<>();
    try {
      String line;
      int lineNumber = 0;
      while ((line = reader.readLine()) != null) {
        lineNumber++;
        if (line.isBlank() || line.startsWith("#")) continue;
        String[] f = line.split("\t", -1);
        if (f.length != 22)
          throw new IllegalStateException(
              "MonsterDb.tsv:" + lineNumber + ": expected 22 columns, got " + f.length);
        try {
          rows.add(new Row(
              f[0], num(f[1]), num(f[2]), num(f[3]), num(f[4]), num(f[5]), num(f[6]),
              Long.parseLong(f[7]), num(f[8]), num(f[9]), num(f[10]), num(f[11]),
              num(f[12]), num(f[13]), num(f[14]), num(f[15]), num(f[16]), num(f[17]),
              num(f[18]), num(f[19]), num(f[20]), num(f[21])));
        } catch (NumberFormatException e) {
          throw new IllegalStateException("MonsterDb.tsv:" + lineNumber + ": malformed number", e);
        }
      }
    } catch (IOException e) {
      throw new UncheckedIOException("failed reading MonsterDb.tsv", e);
    }
    if (rows.isEmpty()) throw new IllegalStateException("MonsterDb.tsv contains no rows");
    return rows;
  }

  private static int num(String token) {
    return Integer.parseInt(token);
  }

  static BufferedReader open(String resource) {
    InputStream stream = MonsterDb.class.getResourceAsStream(resource);
    if (stream == null)
      throw new IllegalStateException("missing classpath resource " + resource
          + " (run scripts/extract-geem2-db.py)");
    return new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8));
  }

  private MonsterDb() {}
}
