package com.mir2.world;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Optional;

/**
 * Authoritative standard-item catalogue imported from the official 1.76 {@code StdItems.DB}
 * (GEEM2 baseline dump, see {@code db/StdItemsDb.tsv} header for provenance). The Java
 * counterpart of the rows {@code TFrmDB.LoadItemsDB} feeds into {@code StdItemList}.
 *
 * <p>Column mapping (dump → {@link StdItem}): the five stat pairs are packed into the
 * Delphi dword layout {@code MakeLong(min, max)} — e.g. {@code Dc, Dc2} become one
 * {@code dc} dword whose low word is the lower bound. The dump's extension columns
 * ({@code Stock}, {@code Color}, elements, insurance, …) have no {@code TStdItem} field
 * and are deliberately not imported. The dump's {@code Reserved} column maps to the distinct
 * {@code TStdItem.Reserved} byte; classic {@code NeedIdentify} is not present in the dump and
 * stays zero, matching {@code TItem.Create} defaults in the Delphi loader.
 *
 * <p>Two names appear twice upstream ({@code 魔法头盔} idx 65/265, {@code 火龙气焰}
 * idx 412/671). Like the Delphi first-hit lookup, the earlier row wins; both rows are kept
 * in the TSV for provenance and documented in its header.
 */
public final class StdItemsDb {

  /** Classpath location of the imported TSV (generated by {@code scripts/extract-geem2-db.py}). */
  public static final String RESOURCE = "/db/StdItemsDb.tsv";

  private static volatile List<StdItem> cached;

  /** All imported items; duplicate names collapse to the first row (Delphi first-hit). */
  public static List<StdItem> all() {
    List<StdItem> items = cached;
    if (items == null) {
      items = List.copyOf(dedupeFirstWins(parse(open())));
      cached = items;
    }
    return items;
  }

  /** Resolves one template by exact name; empty when the catalogue has no such item. */
  public static Optional<StdItem> byName(String name) {
    return all().stream().filter(item -> item.name().equals(name)).findFirst();
  }

  static List<StdItem> parse(BufferedReader reader) {
    List<StdItem> items = new ArrayList<>();
    try {
      String line;
      int lineNumber = 0;
      while ((line = reader.readLine()) != null) {
        lineNumber++;
        if (line.isBlank() || line.startsWith("#")) continue;
        String[] f = line.split("\t", -1);
        if (f.length != 23)
          throw new IllegalStateException(
              "StdItemsDb.tsv:" + lineNumber + ": expected 23 columns, got " + f.length);
        try {
          items.add(new StdItem(
              f[1], /* name */
              num(f[2]),  /* stdMode */
              num(f[3]),  /* shape */
              num(f[4]),  /* weight */
              num(f[5]),  /* aniCount */
              num(f[6]),  /* source (signed byte in Delphi) */
              num(f[7]),  /* reserved */
              0,          /* needIdentify: not present in GEEM2 dump */
              num(f[8]),  /* looks */
              lng(f[9]),  /* duraMax */
              pack(num(f[10]), num(f[11])),  /* ac/ac2 */
              pack(num(f[12]), num(f[13])),  /* mac/mac2 */
              pack(num(f[14]), num(f[15])),  /* dc/dc2 */
              pack(num(f[16]), num(f[17])),  /* mc/mc2 */
              pack(num(f[18]), num(f[19])),  /* sc/sc2 */
              lng(f[20]), /* need */
              lng(f[21]), /* needLevel */
              lng(f[22])  /* price */
          ));
        } catch (IllegalArgumentException e) {
          throw new IllegalStateException("StdItemsDb.tsv:" + lineNumber + ": malformed row " + f[1], e);
        }
      }
    } catch (IOException e) {
      throw new UncheckedIOException("failed reading StdItemsDb.tsv", e);
    }
    if (items.isEmpty()) throw new IllegalStateException("StdItemsDb.tsv contains no rows");
    return items;
  }

  /**
   * Packs a stat pair into the Delphi dword layout. Unlike {@link StdItem#packedRange} this
   * tolerates {@code max < min} pairs (potion rows carry the restore amount in the low word
   * only, e.g. AC=30/AC2=0): the wire representation is the bit field, not a semantic range.
   */
  private static long pack(int low, int high) {
    return ((high & 0xFFFFL) << 16) | (low & 0xFFFFL);
  }

  private static List<StdItem> dedupeFirstWins(List<StdItem> parsed) {
    LinkedHashMap<String, StdItem> byName = new LinkedHashMap<>();
    for (StdItem item : parsed) byName.putIfAbsent(item.name(), item);
    return new ArrayList<>(byName.values());
  }

  private static int num(String token) {
    return Integer.parseInt(token);
  }

  private static long lng(String token) {
    return Long.parseLong(token);
  }

  private static BufferedReader open() {
    InputStream stream = StdItemsDb.class.getResourceAsStream(RESOURCE);
    if (stream == null)
      throw new IllegalStateException("missing classpath resource " + RESOURCE
          + " (run scripts/extract-geem2-db.py)");
    return new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8));
  }

  private StdItemsDb() {}
}
